import type { Metadata } from 'next';
import { ibmPlexSansThai, manrope } from '@/libs/font';
import '@/styles/globals.css';
import '@repo/ui/styles.css';

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}): JSX.Element {
    return (
        <html lang='en'>
            <body className={`${manrope.variable} ${ibmPlexSansThai.variable}`}>
                {children}
            </body>
        </html>
    );
}
