name: OR test

on:
    push:
        branches: ['main', 'develop']
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Build and Test
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm --filter="./packages/*" --filter=or68 build

            - name: Test
              run: pnpm --filter=or68 test
