name: Trigger Vercel Deployments

on:
    push:
        branches: ['develop']
    workflow_dispatch:

jobs:
    run-node-script:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Pull latest changes
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Run Node.js script and Commit
              run: |
                  node ./scripts/deploy.mjs
                  git config --global user.email "${{ secrets.USER_EMAIL }}"
                  git config --global user.name "${{ secrets.USER_NAME }}"
                  git add README.md
                  git commit -m "Trigger Deployments"
                  git push origin ${{ github.ref }}
